"""create production data model

Revision ID: bdcf533a2aff
Revises:
Create Date: 2026-07-29 12:38:05.705937
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bdcf533a2aff"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("safe_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(op.f("ix_audit_events_actor_id"), "audit_events", ["actor_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "idempotency_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_key", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "actor_key", "operation", "idempotency_key", name="uq_idempotency_actor_operation_key"
        ),
    )
    op.create_table(
        "mission_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("graph", sa.JSON(), nullable=False),
        sa.Column("required_slots", sa.JSON(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "version", name="uq_mission_slug_version"),
    )
    op.create_index(op.f("ix_mission_versions_slug"), "mission_versions", ["slug"], unique=False)
    op.create_table(
        "outbox_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("topic", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("topic", "aggregate_id", name="uq_outbox_topic_aggregate"),
    )
    op.create_index(
        op.f("ix_outbox_jobs_aggregate_id"), "outbox_jobs", ["aggregate_id"], unique=False
    )
    op.create_index(op.f("ix_outbox_jobs_status"), "outbox_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_outbox_jobs_topic"), "outbox_jobs", ["topic"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_auth_id", sa.String(length=128), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("access_revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email_hash"), "users", ["email_hash"], unique=False)
    op.create_index(op.f("ix_users_external_auth_id"), "users", ["external_auth_id"], unique=True)
    op.create_table(
        "waitlist_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=False),
        sa.Column("goal", sa.String(length=32), nullable=False),
        sa.Column("is_adult", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("turnstile_verified", sa.Boolean(), nullable=False),
        sa.Column("invitation_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_waitlist_entries_email_hash"), "waitlist_entries", ["email_hash"], unique=True
    )
    op.create_table(
        "consent_records",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("consent_type", sa.String(length=48), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consent_records_user_id"), "consent_records", ["user_id"], unique=False
    )
    op.create_index(
        "ix_consent_user_type_time",
        "consent_records",
        ["user_id", "consent_type", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("email_hash", sa.String(length=64), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["used_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invitations_email_hash"), "invitations", ["email_hash"], unique=False)
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_table(
        "learner_skill_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("skill_key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_key", name="uq_user_skill"),
    )
    op.create_index(
        op.f("ix_learner_skill_states_user_id"), "learner_skill_states", ["user_id"], unique=False
    )
    op.create_table(
        "mission_localizations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mission_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "locale",
            sa.Enum(
                "HI_IN", "TA_IN", "TE_IN", "BN_IN", "MR_IN", name="hintlocale", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_version_id"],
            ["mission_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "mission_version_id", "locale", "version", name="uq_mission_localization_version"
        ),
    )
    op.create_index(
        op.f("ix_mission_localizations_mission_version_id"),
        "mission_localizations",
        ["mission_version_id"],
        unique=False,
    )
    op.create_table(
        "privacy_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("artifact_key", sa.String(length=256), nullable=True),
        sa.Column("artifact_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processor_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("backup_expiry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_privacy_jobs_user_id"), "privacy_jobs", ["user_id"], unique=False)
    op.create_table(
        "profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("age_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "hint_locale",
            sa.Enum(
                "HI_IN", "TA_IN", "TE_IN", "BN_IN", "MR_IN", name="hintlocale", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("level", sa.String(length=24), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("invite_redeemed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("caption_override", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "recommendations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("mission_slug", sa.String(length=64), nullable=False),
        sa.Column("action", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("dismissed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("mission_slug", sa.String(length=64), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("COACH", "REAL_WORLD", name="sessionmode", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "CONNECTING",
                "ACTIVE",
                "RECONNECTING",
                "COMPLETED",
                "ABANDONED",
                "FAILED",
                "EVALUATION_PENDING",
                "EVALUATED",
                name="sessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "hint_locale",
            sa.Enum(
                "HI_IN", "TA_IN", "TE_IN", "BN_IN", "MR_IN", name="hintlocale", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("mission_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("rubric_version", sa.String(length=32), nullable=False),
        sa.Column("localization_version", sa.String(length=32), nullable=False),
        sa.Column("realtime_model", sa.String(length=128), nullable=False),
        sa.Column("evaluator_model", sa.String(length=128), nullable=False),
        sa.Column("frozen_config", sa.JSON(), nullable=False),
        sa.Column("provider_call_id", sa.String(length=128), nullable=True),
        sa.Column("confirmed_sequence", sa.Integer(), nullable=False),
        sa.Column("reconnect_attempts", sa.Integer(), nullable=False),
        sa.Column("caption_assisted", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_mission_slug"), "sessions", ["mission_slug"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "usage_ledgers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column("live_seconds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "usage_date", name="uq_usage_user_date"),
    )
    op.create_index(op.f("ix_usage_ledgers_user_id"), "usage_ledgers", ["user_id"], unique=False)
    op.create_table(
        "assistance_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at_ms", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_assistance_session_sequence"),
    )
    op.create_index(
        op.f("ix_assistance_events_session_id"), "assistance_events", ["session_id"], unique=False
    )
    op.create_table(
        "evaluations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("evaluator_version", sa.String(length=32), nullable=False),
        sa.Column(
            "readiness",
            sa.Enum(
                "FIRST_ATTEMPT",
                "PRACTICING",
                "NEARLY_READY",
                "READY",
                name="readiness",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("deterministic_scores", sa.JSON(), nullable=False),
        sa.Column("semantic_scores", sa.JSON(), nullable=True),
        sa.Column("strengths", sa.JSON(), nullable=False),
        sa.Column("main_obstacle", sa.Text(), nullable=True),
        sa.Column("next_action", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evaluations_session_id"), "evaluations", ["session_id"], unique=True)
    op.create_table(
        "session_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(length=16), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column("slot_events", sa.JSON(), nullable=False),
        sa.Column("started_at_ms", sa.Integer(), nullable=False),
        sa.Column("ended_at_ms", sa.Integer(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "sequence", name="uq_turn_session_sequence"),
    )
    op.create_index(
        op.f("ix_session_turns_session_id"), "session_turns", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_session_turns_session_id"), table_name="session_turns")
    op.drop_table("session_turns")
    op.drop_index(op.f("ix_evaluations_session_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_assistance_events_session_id"), table_name="assistance_events")
    op.drop_table("assistance_events")
    op.drop_index(op.f("ix_usage_ledgers_user_id"), table_name="usage_ledgers")
    op.drop_table("usage_ledgers")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_mission_slug"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_table("profiles")
    op.drop_index(op.f("ix_privacy_jobs_user_id"), table_name="privacy_jobs")
    op.drop_table("privacy_jobs")
    op.drop_index(
        op.f("ix_mission_localizations_mission_version_id"), table_name="mission_localizations"
    )
    op.drop_table("mission_localizations")
    op.drop_index(op.f("ix_learner_skill_states_user_id"), table_name="learner_skill_states")
    op.drop_table("learner_skill_states")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_email_hash"), table_name="invitations")
    op.drop_table("invitations")
    op.drop_index("ix_consent_user_type_time", table_name="consent_records")
    op.drop_index(op.f("ix_consent_records_user_id"), table_name="consent_records")
    op.drop_table("consent_records")
    op.drop_index(op.f("ix_waitlist_entries_email_hash"), table_name="waitlist_entries")
    op.drop_table("waitlist_entries")
    op.drop_index(op.f("ix_users_external_auth_id"), table_name="users")
    op.drop_index(op.f("ix_users_email_hash"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_outbox_jobs_topic"), table_name="outbox_jobs")
    op.drop_index(op.f("ix_outbox_jobs_status"), table_name="outbox_jobs")
    op.drop_index(op.f("ix_outbox_jobs_aggregate_id"), table_name="outbox_jobs")
    op.drop_table("outbox_jobs")
    op.drop_index(op.f("ix_mission_versions_slug"), table_name="mission_versions")
    op.drop_table("mission_versions")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
